---
- name: Create S3 Bucket
  command: "aws s3 mb s3://www.{{ s3_website_domain }} --region {{ s3_website_region }}"
  ignore_errors: yes
  tags:
    - s3
    - s3-create

- name: Upload Static Site to S3
  command: "aws s3 cp {{ s3_website_directory }} s3://www.{{ s3_website_domain }}/ --recursive"
  tags:
    - s3
    - s3-sync

- name: Create Bucket Policy template for S3
  template: src='s3_website_bucket_policy.j2' dest='/tmp/s3_website_bucket_policy.json'
  tags:
    - s3

- name: Set Bucket Policy for S3
  command: "aws s3api put-bucket-policy --bucket www.{{ s3_website_domain }} --policy 'file:///tmp/s3_website_bucket_policy.json'"
  tags:
    - s3

- name: Delete Bucket Policy template for S3
  file: path='/tmp/s3_website_bucket_policy.json' state=absent
  tags:
    - s3

- name: Set S3 Website Config
  command: "aws s3 website s3://www.{{ s3_website_domain }}/ --index-document {{ s3_website_index_document }} --error-document {{ s3_website_error_document }}"
  tags:
    - s3
